// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: c575929542
// Version Date: 2020年 6月17日 星期三 04时40分15秒 UTC

// Package grpc provides a gRPC client for the Greeting service.
package grpc

import (
	"context"
	"github.com/pkg/errors"
	"google.golang.org/grpc"
	"google.golang.org/grpc/metadata"

	"github.com/go-kit/kit/endpoint"
	grpctransport "github.com/go-kit/kit/transport/grpc"

	// This Service
	"github.com/rachihoaoi/daily-exercise.git/truss_sample/internal/hello/svc"
	pb "github.com/rachihoaoi/daily-exercise.git/truss_sample/pbs"
)

// New returns an service backed by a gRPC client connection. It is the
// responsibility of the caller to dial, and later close, the connection.
func New(conn *grpc.ClientConn, options ...ClientOption) (pb.GreetingServer, error) {
	var cc clientConfig

	for _, f := range options {
		err := f(&cc)
		if err != nil {
			return nil, errors.Wrap(err, "cannot apply option")
		}
	}

	clientOptions := []grpctransport.ClientOption{
		grpctransport.ClientBefore(
			contextValuesToGRPCMetadata(cc.headers)),
	}
	var sayhelloEndpoint endpoint.Endpoint
	{
		sayhelloEndpoint = grpctransport.NewClient(
			conn,
			"pb.Greeting",
			"SayHello",
			EncodeGRPCSayHelloRequest,
			DecodeGRPCSayHelloResponse,
			pb.SayHelloResponse{},
			clientOptions...,
		).Endpoint()
	}

	return svc.Endpoints{
		SayHelloEndpoint: sayhelloEndpoint,
	}, nil
}

// GRPC Client Decode

// DecodeGRPCSayHelloResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC sayhello reply to a user-domain sayhello response. Primarily useful in a client.
func DecodeGRPCSayHelloResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.SayHelloResponse)
	return reply, nil
}

// GRPC Client Encode

// EncodeGRPCSayHelloRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain sayhello request to a gRPC sayhello request. Primarily useful in a client.
func EncodeGRPCSayHelloRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.SayHelloRequest)
	return req, nil
}

type clientConfig struct {
	headers []string
}

// ClientOption is a function that modifies the client config
type ClientOption func(*clientConfig) error

func CtxValuesToSend(keys ...string) ClientOption {
	return func(o *clientConfig) error {
		o.headers = keys
		return nil
	}
}

func contextValuesToGRPCMetadata(keys []string) grpctransport.ClientRequestFunc {
	return func(ctx context.Context, md *metadata.MD) context.Context {
		var pairs []string
		for _, k := range keys {
			if v, ok := ctx.Value(k).(string); ok {
				pairs = append(pairs, k, v)
			}
		}

		if pairs != nil {
			*md = metadata.Join(*md, metadata.Pairs(pairs...))
		}

		return ctx
	}
}
